FROM node:13.12.0-alpine as builder
WORKDIR /usr/src/app
COPY $PWD/app-web/package.json ./
COPY $PWD/app-web/package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY $PWD/app-web/ .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"] 